---
platform: linux

image_resource:
  type: docker-image
  source: {repository: busybox}

inputs:
  - name: resource-app-repo

run:
  path: resource-app-repo/ci/tasks/alert.sh
  args: [
    --input-dir, resource-app-repo
  ]
