---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

params:
  MAVEN_OPTS:
  MAVEN_CONFIG:

inputs:
  - name: resource-app-repo
  - name: version

outputs:
  - name: build

run:
  path: resource-app-repo/ci/tasks/build.sh
  args: [
    --input-dir, resource-app-repo,
    --output-dir, build,
    --version-file, version/number,
    --artifactId, reaction-app,
    --packaging, jar
  ]
