---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

inputs:
  - name: resource-app-repo

run:
  path: resource-app-repo/ci/tasks/integration.sh
  args: [
    --input-dir, resource-app-repo
  ]
