platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: latest

inputs:
  - name: resource-app-repo

outputs:
  - name: output

run:
  path: sh
  args:
    - resource-app-repo/ci/tasks/maven-package.sh
