---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

params:
  MAVEN_OPTS:
  MAVEN_CONFIG:

inputs:
  - name: resource-app-repo

outputs:
  - name: logs-out

run:
  path: resource-app-repo/ci/tasks/unit.sh
  args: [
    --input-dir, resource-app-repo
  ]