---
resources:
- name: resource-app-repo
  type: git
  source:
    uri: https://github.com/poprygun/reaction.git
    branch: master

- name: candidate-release
  type: s3
  source:
    bucket: {{s3-bucket-release-candidates}}
    regexp: reaction-app-(.*).jar
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    endpoint: {{s3-endpoint}}

- name: final-release
  type: s3
  source:
    bucket: {{s3-bucket-release-final}}
    regexp: reaction-app-(.*).jar
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    endpoint: {{s3-endpoint}}

- name: resource-deploy-app
  type: cf
  source:
    api: https://api.local.pcfdev.io
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: {{cf-space}}
    skip_cert_check: true

- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:poprygun/reaction.git
    branch: version
    file: number
    initial_version: 0.0.1-SNAPSHOT
    private_key: {{git-private-key}}

- name: send-an-email
  type: email
  source:
    smtp:
      host: {{smtp-host}}
      port: {{smtp-port}}
      username: {{smtp-username}}
      password: {{smtp-password}}
    from: {{email-from}}
    to: [ poprygun@hotmail.com ]

resource_types:
  - name: email
    type: docker-image
    source:
      repository: pcfseceng/email-resource

jobs:
- name: unit-test
  public: true
  plan:
    - do:
      - get: resource-app-repo
        trigger: true
#      - task: prep-sha-email
#        file: resource-app-repo/ci/tasks/prep-sha-email.yml
      - task: unit
        file: resource-app-repo/ci/tasks/unit.yml
        params: &MAVENPARAMS
          MAVEN_OPTS: {{maven-opts}}
          MAVEN_CONFIG: {{maven-config}}
      on_success:
        put: send-an-email
        params:
          subject: email-out/generated-subject
          body: email-out/generated-body
      on_failure:
        put: send-an-email
        params:
          subject: email-out/generated-subject
          body: email-out/generated-body
#      on_failure:
#        task: alert
#        file: resource-app-repo/ci/tasks/alert.yml
#        params:
#          MESSAGE: 'here we go again'

- name: build-artifact
  serial_groups: [ version ]
  plan:
    - get: resource-app-repo
      passed: [ unit-test ]
      trigger: true
    - get: version
      params: { bump: patch }
    - task: build
      file: resource-app-repo/ci/tasks/build.yml
      params:
        <<: *MAVENPARAMS
    - put: candidate-release
      params: { file: build/reaction-app-*.jar }
    - put: version
      params: { file: version/number }

- name: integration-test
  serial: true
  plan:
    - get: candidate-release
      trigger: true
      passed: [ build-artifact ]
    - get: resource-app-repo
      passed: [ build-artifact ]
    - get: version
      passed: [ build-artifact ]
    - task: prepare-integration
      file: resource-app-repo/ci/tasks/prepare-integration.yml
      params:
        CF_MANIFEST_HOST: {{cf-manifest-host}}
    - put: resource-deploy-app
      params:
        manifest: prepare-integration/manifest.yml
    - task: integration
      file: resource-app-repo/ci/tasks/integration.yml
      params:
        <<: *MAVENPARAMS

- name: deploy
  serial_groups: [ version ]
  plan:
    - get: candidate-release
      passed: [ integration-test ]
    - get: resource-app-repo
      passed: [ integration-test ]
    - get: version
      params: { bump: final }
    - task: prepare-final
      file: resource-app-repo/ci/tasks/prepare-final.yml
    - put: final-release
      params: { file: prepare-final/reaction-app-*.jar }
    - put: version
      params: { file: version/number }

- name: patch
  serial_groups: [ version ]
  plan:
    - get: version
      passed: [ deploy ]
      trigger: true
    - put: version
      params: { bump: patch, pre: rc }